version: "3.7"

services:
  ###############
  # LITECOIN LND
  ###############

  lnd-ltc:
    image: crypdex/lnd:0.6
    restart: on-failure
    container_name: lnd-ltc
    command:
      --litecoin.active
      --litecoin.mainnet
      --litecoin.node=litecoind
      --litecoind.rpchost=litecoin
      --litecoind.rpcuser=friendfund
      --litecoind.rpcpass=friendfund
      --litecoind.zmqpubrawblock=tcp://litecoin:28333
      --litecoind.zmqpubrawtx=tcp://litecoin:28334
      --rpclisten=0.0.0.0:10009
    depends_on:
      - litecoin
    volumes:
      - /Volumes/FriendFund/data/lnd:/home/lnd/.lnd
    ports:
      - 9735:9735
      - 10009:10009 # expose the RPC so lncli can get in touch


  ###########
  # LITECOIN
  ###########

  litecoin:
    image: crypdex/litecoin-core:0.17
    container_name: litecoin # Without this, lnd cannot reach the litecoin daemon
    restart: on-failure
    # -zmq* and -rpcallowip flags are necessary
    command:
      -rpcuser=friendfund
      -rpcpassword=friendfund
      -printtoconsole
      -txindex
      -rpcallowip=0.0.0.0/0
      -zmqpubrawblock=tcp://0.0.0.0:28333
      -zmqpubrawtx=tcp://0.0.0.0:28334
    ports:
      - 9332:9332 # RPC
      - 9333:9333 # P2P
    volumes:
      - /Volumes/FriendFund/data/litecoin:/home/litecoin/.litecoin
